package com.immy.beans;

import java.math.BigDecimal;
import java.util.Date;

public class Product {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT.title
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String title;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT.price
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String price;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT.image_url
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String imageUrl;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT.status
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT.description
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String description;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT.produce_url
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String produceUrl;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT.type_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String typeId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT.create_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private Date createTime;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT.id
	 * @return  the value of PRODUCT.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT.id
	 * @param id  the value for PRODUCT.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT.title
	 * @return  the value of PRODUCT.title
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT.title
	 * @param title  the value for PRODUCT.title
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT.price
	 * @return  the value of PRODUCT.price
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT.price
	 * @param price  the value for PRODUCT.price
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT.image_url
	 * @return  the value of PRODUCT.image_url
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT.image_url
	 * @param imageUrl  the value for PRODUCT.image_url
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT.status
	 * @return  the value of PRODUCT.status
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT.status
	 * @param status  the value for PRODUCT.status
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT.description
	 * @return  the value of PRODUCT.description
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT.description
	 * @param description  the value for PRODUCT.description
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT.produce_url
	 * @return  the value of PRODUCT.produce_url
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getProduceUrl() {
		return produceUrl;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT.produce_url
	 * @param produceUrl  the value for PRODUCT.produce_url
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setProduceUrl(String produceUrl) {
		this.produceUrl = produceUrl;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT.type_id
	 * @return  the value of PRODUCT.type_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT.type_id
	 * @param typeId  the value for PRODUCT.type_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT.create_time
	 * @return  the value of PRODUCT.create_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT.create_time
	 * @param createTime  the value for PRODUCT.create_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}