package com.immy.beans;

import java.util.Date;

public class ProductType {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT_TYPE.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT_TYPE.type_name
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String typeName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column PRODUCT_TYPE.type_description
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String typeDescription;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT_TYPE.id
	 * @return  the value of PRODUCT_TYPE.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT_TYPE.id
	 * @param id  the value for PRODUCT_TYPE.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT_TYPE.type_name
	 * @return  the value of PRODUCT_TYPE.type_name
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT_TYPE.type_name
	 * @param typeName  the value for PRODUCT_TYPE.type_name
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column PRODUCT_TYPE.type_description
	 * @return  the value of PRODUCT_TYPE.type_description
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getTypeDescription() {
		return typeDescription;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column PRODUCT_TYPE.type_description
	 * @param typeDescription  the value for PRODUCT_TYPE.type_description
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setTypeDescription(String typeDescription) {
		this.typeDescription = typeDescription;
	}
}