package com.immy.beans;

import java.util.Date;

public class User {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.phone
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String phone;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.passwd
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String passwd;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.source
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String source;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.role_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String roleId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.status
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.tel
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String tel;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.email
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.login_name
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String loginName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.real_name
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String realName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.last_login_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.remark
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String remark;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER.create_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private Date createTime;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.id
	 * @return  the value of USER.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.id
	 * @param id  the value for USER.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.phone
	 * @return  the value of USER.phone
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.phone
	 * @param phone  the value for USER.phone
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.passwd
	 * @return  the value of USER.passwd
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getPasswd() {
		return passwd;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.passwd
	 * @param passwd  the value for USER.passwd
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.source
	 * @return  the value of USER.source
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.source
	 * @param source  the value for USER.source
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setSource(String source) {
		this.source = source;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.role_id
	 * @return  the value of USER.role_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.role_id
	 * @param roleId  the value for USER.role_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.status
	 * @return  the value of USER.status
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.status
	 * @param status  the value for USER.status
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.tel
	 * @return  the value of USER.tel
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.tel
	 * @param tel  the value for USER.tel
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.email
	 * @return  the value of USER.email
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.email
	 * @param email  the value for USER.email
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.login_name
	 * @return  the value of USER.login_name
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.login_name
	 * @param loginName  the value for USER.login_name
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.real_name
	 * @return  the value of USER.real_name
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.real_name
	 * @param realName  the value for USER.real_name
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.last_login_time
	 * @return  the value of USER.last_login_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.last_login_time
	 * @param lastLoginTime  the value for USER.last_login_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.remark
	 * @return  the value of USER.remark
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.remark
	 * @param remark  the value for USER.remark
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER.create_time
	 * @return  the value of USER.create_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER.create_time
	 * @param createTime  the value for USER.create_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}