package com.immy.beans;

import java.util.Date;

public class UserProduct {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER_PRODUCT.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER_PRODUCT.user_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String userId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER_PRODUCT.product_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String productId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER_PRODUCT.status
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private String status;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column USER_PRODUCT.create_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private Date createTime;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER_PRODUCT.id
	 * @return  the value of USER_PRODUCT.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER_PRODUCT.id
	 * @param id  the value for USER_PRODUCT.id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER_PRODUCT.user_id
	 * @return  the value of USER_PRODUCT.user_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER_PRODUCT.user_id
	 * @param userId  the value for USER_PRODUCT.user_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER_PRODUCT.product_id
	 * @return  the value of USER_PRODUCT.product_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER_PRODUCT.product_id
	 * @param productId  the value for USER_PRODUCT.product_id
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER_PRODUCT.status
	 * @return  the value of USER_PRODUCT.status
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER_PRODUCT.status
	 * @param status  the value for USER_PRODUCT.status
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column USER_PRODUCT.create_time
	 * @return  the value of USER_PRODUCT.create_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column USER_PRODUCT.create_time
	 * @param createTime  the value for USER_PRODUCT.create_time
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}