package com.immy.dao;

import com.immy.beans.ProductType;
import com.immy.beans.ProductTypeExample;
import java.util.List;

public interface ProductTypeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int countByExample(ProductTypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int deleteByExample(ProductTypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	void insert(ProductType record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	void insertSelective(ProductType record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	List selectByExample(ProductTypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	ProductType selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByExampleSelective(ProductType record, ProductTypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByExample(ProductType record, ProductTypeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByPrimaryKeySelective(ProductType record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByPrimaryKey(ProductType record);
}