package com.immy.dao;

import com.immy.beans.ProductType;
import com.immy.beans.ProductTypeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProductTypeDAOImpl extends SqlMapClientDaoSupport implements ProductTypeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public ProductTypeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int countByExample(ProductTypeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"PRODUCT_TYPE.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int deleteByExample(ProductTypeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"PRODUCT_TYPE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		ProductType key = new ProductType();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"PRODUCT_TYPE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void insert(ProductType record) {
		getSqlMapClientTemplate().insert("PRODUCT_TYPE.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void insertSelective(ProductType record) {
		getSqlMapClientTemplate().insert(
				"PRODUCT_TYPE.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public List selectByExample(ProductTypeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"PRODUCT_TYPE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public ProductType selectByPrimaryKey(String id) {
		ProductType key = new ProductType();
		key.setId(id);
		ProductType record = (ProductType) getSqlMapClientTemplate()
				.queryForObject(
						"PRODUCT_TYPE.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByExampleSelective(ProductType record,
			ProductTypeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"PRODUCT_TYPE.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByExample(ProductType record, ProductTypeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"PRODUCT_TYPE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByPrimaryKeySelective(ProductType record) {
		int rows = getSqlMapClientTemplate().update(
				"PRODUCT_TYPE.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByPrimaryKey(ProductType record) {
		int rows = getSqlMapClientTemplate().update(
				"PRODUCT_TYPE.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table PRODUCT_TYPE
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private static class UpdateByExampleParms extends ProductTypeExample {
		private Object record;

		public UpdateByExampleParms(Object record, ProductTypeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}