package com.immy.dao;

import com.immy.beans.Product;
import com.immy.beans.ProductExample;
import java.util.List;

public interface ProductDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int countByExample(ProductExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int deleteByExample(ProductExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	void insert(Product record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	void insertSelective(Product record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	List selectByExample(ProductExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	Product selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByExampleSelective(Product record, ProductExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByExample(Product record, ProductExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByPrimaryKeySelective(Product record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByPrimaryKey(Product record);
}