package com.immy.dao;

import com.immy.beans.User;
import com.immy.beans.UserExample;
import java.util.List;

public interface UserDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int countByExample(UserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	void insert(User record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	void insertSelective(User record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	List selectByExample(UserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	User selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByExampleSelective(User record, UserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByExample(User record, UserExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	int updateByPrimaryKey(User record);
}