package com.immy.dao;

import com.immy.beans.UserProduct;
import com.immy.beans.UserProductExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserProductDAOImpl extends SqlMapClientDaoSupport implements UserProductDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public UserProductDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int countByExample(UserProductExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"USER_PRODUCT.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int deleteByExample(UserProductExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"USER_PRODUCT.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		UserProduct key = new UserProduct();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"USER_PRODUCT.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void insert(UserProduct record) {
		getSqlMapClientTemplate().insert("USER_PRODUCT.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void insertSelective(UserProduct record) {
		getSqlMapClientTemplate().insert(
				"USER_PRODUCT.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public List selectByExample(UserProductExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"USER_PRODUCT.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public UserProduct selectByPrimaryKey(String id) {
		UserProduct key = new UserProduct();
		key.setId(id);
		UserProduct record = (UserProduct) getSqlMapClientTemplate()
				.queryForObject(
						"USER_PRODUCT.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByExampleSelective(UserProduct record,
			UserProductExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"USER_PRODUCT.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByExample(UserProduct record, UserProductExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"USER_PRODUCT.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByPrimaryKeySelective(UserProduct record) {
		int rows = getSqlMapClientTemplate().update(
				"USER_PRODUCT.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByPrimaryKey(UserProduct record) {
		int rows = getSqlMapClientTemplate().update(
				"USER_PRODUCT.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table USER_PRODUCT
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private static class UpdateByExampleParms extends UserProductExample {
		private Object record;

		public UpdateByExampleParms(Object record, UserProductExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}