package com.immy.dao;

import com.immy.beans.User;
import com.immy.beans.UserExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserDAOImpl extends SqlMapClientDaoSupport implements UserDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public UserDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int countByExample(UserExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"USER.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int deleteByExample(UserExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"USER.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int deleteByPrimaryKey(String id) {
		User key = new User();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"USER.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void insert(User record) {
		getSqlMapClientTemplate().insert("USER.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public void insertSelective(User record) {
		getSqlMapClientTemplate().insert(
				"USER.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public List selectByExample(UserExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"USER.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public User selectByPrimaryKey(String id) {
		User key = new User();
		key.setId(id);
		User record = (User) getSqlMapClientTemplate().queryForObject(
				"USER.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByExampleSelective(User record, UserExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"USER.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByExample(User record, UserExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"USER.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByPrimaryKeySelective(User record) {
		int rows = getSqlMapClientTemplate().update(
				"USER.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	public int updateByPrimaryKey(User record) {
		int rows = getSqlMapClientTemplate().update(
				"USER.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table USER
	 * @ibatorgenerated  Fri May 22 08:54:35 CST 2015
	 */
	private static class UpdateByExampleParms extends UserExample {
		private Object record;

		public UpdateByExampleParms(Object record, UserExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}